### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by FauFra** [oracle-actions/run-oci-cli-command#17]
I tried yaml example reported on README, but I get a fail on the first execution step.

```
Installing Oracle Cloud Infrastructure CLI
  /usr/bin/python -m pip install oci-cli
  Defaulting to user installation because normal site-packages is not writeable
  Collecting oci-cli
    Downloading oci_cli-3.21.0-py3-none-any.whl (33.6 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.6/33.6 MB 84.8 MB/s eta 0:00:00
  Collecting pyOpenSSL>=22.1.0
    Downloading pyOpenSSL-22.1.0-py3-none-any.whl (57 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 KB 24.3 MB/s eta 0:00:00
  Collecting oci==2.89.0
    Downloading oci-2.89.0-py2.py3-none-any.whl (18.5 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 125.5 MB/s eta 0:00:00
  Collecting jmespath==0.10.0
    Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
  Requirement already satisfied: six>=1.15.0 in /usr/lib/python3/dist-packages (from oci-cli) (1.16.0)
  Collecting click==7.1.2
    Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.8/82.8 KB 30.7 MB/s eta 0:00:00
  Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from oci-cli) (2020.6.20)
  Requirement already satisfied: pytz>=2016.10 in /usr/lib/python3/dist-packages (from oci-cli) (2022.1)
  Collecting prompt-toolkit==3.0.29
    Downloading prompt_toolkit-3.0.29-py3-none-any.whl (381 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.5/381.5 KB 95.8 MB/s eta 0:00:00
  Collecting terminaltables==3.1.0
    Downloading terminaltables-3.1.0.tar.gz (12 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Requirement already satisfied: PyYAML<6,>=5.4 in /usr/lib/python3/dist-packages (from oci-cli) (5.4.1)
  Collecting arrow>=1.0.0
    Downloading arrow-1.2.3-py3-none-any.whl (66 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 KB 27.5 MB/s eta 0:00:00
  Requirement already satisfied: cryptography<=39.0.0,>=3.2.1 in /usr/lib/python3/dist-packages (from oci-cli) (3.4.8)
  Collecting python-dateutil<3.0.0,>=2.5.3
    Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 63.4 MB/s eta 0:00:00
  Collecting circuitbreaker<2.0.0,>=1.3.1
    Downloading circuitbreaker-1.4.0.tar.gz (9.7 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting wcwidth
    Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
  Collecting cryptography<=39.0.0,>=3.2.1
    Downloading cryptography-38.0.4-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 149.4 MB/s eta 0:00:00
  Collecting cffi>=1.12
    Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 KB 105.2 MB/s eta 0:00:00
  Collecting pycparser
    Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 54.2 MB/s eta 0:00:00
  Building wheels for collected packages: terminaltables, circuitbreaker
    Building wheel for terminaltables (setup.py): started
    Building wheel for terminaltables (setup.py): finished with status 'done'
    Created wheel for terminaltables: filename=terminaltables-3.1.0-py3-none-any.whl size=15355 sha256=e67752bfc9a82d960a38dd3482d50972a563e42ed4ba558dcf1ce3725f367ecb
    Stored in directory: /home/runner/.cache/pip/wheels/0e/e1/98/126eccfa07627229dd8299be9445fcf626f52e636268996bb6
    Building wheel for circuitbreaker (setup.py): started
    Building wheel for circuitbreaker (setup.py): finished with status 'done'
    Created wheel for circuitbreaker: filename=circuitbreaker-1.4.0-py3-none-any.whl size=7522 sha256=786f[13](https://github.com/FauFra/cicloturismo/actions/runs/3669110704/jobs/6202702752#step:2:14)476968dc76cf3873f9e5ae9b5dcbd86231d542[15](https://github.com/FauFra/cicloturismo/actions/runs/3669110704/jobs/6202702752#step:2:16)bc0350ac55c3697da6
    Stored in directory: /home/runner/.cache/pip/wheels/3c/be/64/266b6ce2ef1130de5e4[19](https://github.com/FauFra/cicloturismo/actions/runs/3669110704/jobs/6202702752#step:2:20)f04805acbb2df5a4ab1b91348f25b
  Successfully built terminaltables circuitbreaker
  Installing collected packages: wcwidth, terminaltables, circuitbreaker, python-dateutil, pycparser, prompt-toolkit, jmespath, click, cffi, arrow, cryptography, pyOpenSSL, oci, oci-cli
  Successfully installed arrow-1.2.3 cffi-1.15.1 circuitbreaker-1.4.0 click-7.1.2 cryptography-38.0.4 jmespath-0.10.0 oci-2.89.0 oci-cli-3.[21](https://github.com/FauFra/cicloturismo/actions/runs/3669110704/jobs/6202702752#step:2:22).0 prompt-toolkit-3.0.29 pyOpenSSL-[22](https://github.com/FauFra/cicloturismo/actions/runs/3669110704/jobs/6202702752#step:2:23).1.0 pycparser-2.21 python-dateutil-2.8.2 terminaltables-3.1.0 wcwidth-0.2.5
Executing Oracle Cloud Infrastructure CLI command
Error: The process '/home/runner/.local/bin/oci' failed with exit code 1
```

`steps` snippet is 
```
steps:
      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.1
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='testing'].id"

      - name: Retrieve the display name and shape of the instances in my compartment
        uses: oracle-actions/run-oci-cli-command@v1.1
        id: find-instances
        with:
          command: 'compute instance list --compartment-id ${{ steps.find-compartment-id.outputs.raw_output }}'
          query: 'data[*].{name: \"display-name\", shape: shape}'

      - name: List the display name and shape of the instances in my compartment
        run: |
          echo ${{ steps.find-my-compartment-instances.outputs.output }} | jq .
```
