### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by ukendiran** [oracle-actions/run-oci-cli-command#23]
32s
Run oracle-actions/run-oci-cli-command@v1.1.1
Installing Oracle Cloud Infrastructure CLI
Executing Oracle Cloud Infrastructure CLI command
Error: The process '/home/runner/.local/bin/oci' failed with exit code 1

**Comment by Djelibeybi** [comment]
Sorry, but this isn't enough information to start troubleshooting. Can you please provide a link to the workflow or at least the `oci` command you're trying to run?

**Comment by lucasaugustomcc** [comment]
I have the same issue. The command works when I run locally using the same credentials (just copied and pasted from my config to github secrets):
`oci os object bulk-upload -ns XX -bn YY --src-dir directory --overwrite`

**Workflow**
```
name: Deploy using OCI bucket

on:
  push:
    branches:
      - main

jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Upload dags folder to object storage
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Upload folder
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: upload-objects
        with:
          command: 'os object bulk-upload -ns XX -bn YY --src-dir directory --overwrite'
          
          
```

**Output**

Run oracle-actions/run-oci-cli-command@v1.1.1
Installing Oracle Cloud Infrastructure CLI
Executing Oracle Cloud Infrastructure CLI command
Error: The process '/home/runner/.local/bin/oci' failed with exit code 1
