### ISSUE TITLE
Error: Why is json input stripped on quotes?

### ISSUE THREAD

**Issue by ammbra** [oracle-actions/run-oci-cli-command#25]
Hello,
 Running (command and result copy pasted from the output): 
```
with:
    command: network route-table update --force --route-rules '[{"destination":"0.0.0.0/0","destinationType":"CIDR_BLOCK","networkEntityId":"ocid1.internetgateway.oc1"}]' --rt-id "ocid1.routetable.oc1"
    query: data
    silent: false
```

creates this cmd with errors:

```
Executing Oracle Cloud Infrastructure CLI command
/home/runner/.local/bin/oci network route-table update --force --route-rules '[{destination:0.0.0.0/0,destinationType:CIDR_BLOCK,networkEntityId:ocid1.internetgateway.oc1]' -rt-id ocid1.routetable.oc1
Parameter 'route_rules' must be in JSON format.
For help with formatting JSON input see our documentation here: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliusing.htm#ManagingCLIInputandOutput
```

Can you please provide a solution to overcome this?

Thank you
