### ISSUE TITLE
raw_output return 0

### ISSUE THREAD

**Issue by DwarKapex** [oracle-actions/run-oci-cli-command#31]
I tried the latest version of this Actions.
Here is my GitHub Action yaml:
```
name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.3.0
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id-in-subtree=true'
          query: "data[?name=='jax'].id"
          silent: false
      - name: List the display name and shape of the instances in my compartment
        run: |
          echo output=${{ steps.find-compartment-id.outputs.output }}
          echo raw_output=${{ steps.find-compartment-id.outputs.raw_output }}
```

For some reason `raw_output` is `0`:
```
1. Run oracle-actions/run-oci-cli-command@v1.3.0
Installing Oracle Cloud Infrastructure CLI
Executing Oracle Cloud Infrastructure CLI command
/home/runner/.local/bin/oci --query data[?name=='jax'].id iam compartment list --compartment-id-in-subtree=true
[
  <reasonable_output>
]

2. Run second step
  shell: /usr/bin/bash -e {0}
  env:
    OCI_CLI_USER: ***
    OCI_CLI_TENANCY: ***
    OCI_CLI_FINGERPRINT: ***
    OCI_CLI_KEY_CONTENT: ***
    OCI_CLI_REGION: ***
output=<reasonable_output>
raw_output=0
```
